name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  no-host-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --depth 1 sources/sfml sources/litergss2
      - run: scripts/check-no-host-code.sh
